// Test generated by RoostGPT for test eon-test using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.controller;

import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;
import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;

@SpringBootTest
public class ProductController_getAllProducts_7e38cc05f6_Test {

    @InjectMocks
    ProductController productController;

    @Mock
    ProductRepository productRepository;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetAllProducts() {
        Product product1 = new Product();
        product1.setId(1);
        product1.setName("Product1");

        Product product2 = new Product();
        product2.setId(2);
        product2.setName("Product2");

        List<Product> productList = Arrays.asList(product1, product2);

        when(productRepository.findAll()).thenReturn(productList);

        List<Product> result = productController.getAllProducts();
        assertEquals(productList, result);
    }

    @Test
    public void testGetAllProducts_NoProducts() {
        List<Product> emptyList = Arrays.asList();

        when(productRepository.findAll()).thenReturn(emptyList);

        List<Product> result = productController.getAllProducts();
        assertEquals(emptyList, result);
    }
}
