// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setPrice_8f1e19b496_Test {

    private Product product;

    @BeforeEach
    public void setup() {
        product = new Product();
    }

    @Test
    public void testSetPrice_PositivePrice() {
        double price = 100.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "The set price should match the get price for positive values");
    }

    @Test
    public void testSetPrice_ZeroPrice() {
        double price = 0.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "The set price should match the get price for zero value");
    }

    @Test
    public void testSetPrice_NegativePrice() {
        double price = -100.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "The set price should match the get price for negative values");
    }
}
