// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Product_setDescription_b4ccff923c_Test {

    private Product product;

    @BeforeEach
    void setUp() {
        product = new Product();
    }

    @Test
    void testSetDescription_Success() {
        String description = "This is a test product description";
        product.setDescription(description);
        assertEquals(description, product.getDescription());
    }

    @Test
    void testSetDescription_Null() {
        String description = null;
        product.setDescription(description);
        assertNull(product.getDescription());
    }

    @Test
    void testSetDescription_Empty() {
        String description = "";
        product.setDescription(description);
        assertEquals(description, product.getDescription());
    }
}
