// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getId_ba349b1eff_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testGetIdWhenIdIsNull() {
        product.setId(null); // TODO: set the id as per your requirement
        Long expected = null;
        Long actual = product.getId();
        assertEquals(expected, actual, "The id should be null");
    }

    @Test
    public void testGetIdWhenIdIsNotNull() {
        Long expected = 1L; // TODO: set the id as per your requirement
        product.setId(expected);
        Long actual = product.getId();
        assertEquals(expected, actual, "The id should be 1");
    }
}
