// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getPrice_d2cb73a47d_Test {

    @InjectMocks
    private Product product;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetPrice_positiveScenario() {
        double expectedPrice = 100.0;
        product.setPrice(expectedPrice);
        double actualPrice = product.getPrice();
        assertEquals(expectedPrice, actualPrice, "The expected price does not match the actual price");
    }

    @Test
    public void testGetPrice_zeroScenario() {
        double expectedPrice = 0.0;
        product.setPrice(expectedPrice);
        double actualPrice = product.getPrice();
        assertEquals(expectedPrice, actualPrice, "The expected price does not match the actual price");
    }

    @Test
    public void testGetPrice_negativeScenario() {
        double expectedPrice = -100.0;
        product.setPrice(expectedPrice);
        double actualPrice = product.getPrice();
        assertEquals(expectedPrice, actualPrice, "The expected price does not match the actual price");
    }
}
